spring.application.name=smart-pos-system


# Database connection URL
spring.datasource.url=jdbc:mysql://localhost:3306/posDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
&allowPublicKeyRetrieval=true
&serverTimezone=UTC

# Database username
spring.datasource.username=root

# Database password
spring.datasource.password=Husain@78607

# MySQL driver class name (for Connector/J 8.x and above)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate properties (optional, for schema management)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
